# Generated by Django 4.1 on 2022-08-04 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('ci', models.CharField(max_length=150, unique=True, verbose_name='CI')),
                ('data_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
