# Generated by Django 4.1 on 2022-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=150, verbose_name='Motivo')),
                ('cost', models.IntegerField(default=0, verbose_name='Costo')),
                ('prov_name', models.CharField(max_length=150, verbose_name='Nombre de proveedor')),
                ('descrip', models.CharField(max_length=150, verbose_name='Descripcion de compra')),
            ],
        ),
    ]
