# Generated by Django 4.1 on 2022-09-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_buy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ['id'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
