# Generated by Django 4.1 on 2022-09-07 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_buy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
