# Generated by Django 4.1 on 2022-09-07 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_buy_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
    ]
