# Generated by Django 4.1 on 2022-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_category_date_creation_category_date_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='uni',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
