# Generated by Django 4.1 on 2022-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_buy_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='uni',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad total en su unidad'),
        ),
    ]
