# Generated by Django 4.1 on 2022-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(default=1, max_length=150, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
