# Generated by Django 4.1 on 2022-10-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_remove_category_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_update',
        ),
    ]
