# Generated by Django 4.1 on 2022-11-09 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='cant',
        ),
        migrations.AddField(
            model_name='product',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Stock'),
        ),
    ]
