# Generated by Django 4.1 on 2022-11-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_methodpay_remove_product_cant_product_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad'),
        ),
    ]
