# Generated by Django 4.1 on 2022-11-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_detsale_cant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='cant',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
