# Generated by Django 4.1 on 2022-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_detsale_cant_alter_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MethodPay',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='cant',
            field=models.IntegerField(default=0),
        ),
    ]
