# Generated by Django 4.1 on 2022-11-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_delete_methodpay_remove_product_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cant',
            new_name='stock',
        ),
    ]
