# Generated by Django 4.1 on 2022-11-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_supplier_delete_employee_delete_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
