# Generated by Django 4.1 on 2022-11-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_delete_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
    ]
