# Generated by Django 4.1 on 2022-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_rename_dni_supplier_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ci',
            field=models.CharField(max_length=10, unique=True, verbose_name='RUC'),
        ),
    ]
