# Generated by Django 4.1 on 2022-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_alter_supplier_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unity',
            name='uname',
        ),
        migrations.AddField(
            model_name='unity',
            name='name',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Unidad de medida'),
            preserve_default=False,
        ),
    ]
