# Generated by Django 4.1 on 2022-11-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_rename_pc_productbrut_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrut',
            name='date_joined',
        ),
    ]
