# Generated by Django 4.1 on 2022-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_remove_productbrut_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Correo electronico'),
            preserve_default=False,
        ),
    ]
