# Generated by Django 4.1 on 2022-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_remove_supplier_date_joined_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=150, unique=True, verbose_name='Correo electronico'),
        ),
    ]
