# Generated by Django 4.1 on 2022-11-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_alter_supplier_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBrut',
            new_name='Materials',
        ),
    ]
