# Generated by Django 4.1 on 2022-11-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_categorymaterials_materials_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaterials',
            name='unity',
            field=models.CharField(choices=[('Ls', 'Litros'), ('kg', 'Kilogramo'), ('Un', 'Unidades')], default='ls', max_length=10, verbose_name='Unidad de medida'),
        ),
    ]
