# Generated by Django 4.1 on 2022-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_categorymaterials_unity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='uni',
        ),
        migrations.AlterField(
            model_name='categorymaterials',
            name='unity',
            field=models.CharField(choices=[('Litros', 'Litros'), ('Kilogramo', 'Kilogramo'), ('Unidades', 'Unidades')], default='ls', max_length=10, verbose_name='Unidad de medida'),
        ),
        migrations.DeleteModel(
            name='Unity',
        ),
    ]
