# Generated by Django 4.1 on 2022-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_alter_materials_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra'),
        ),
    ]
