# Generated by Django 4.1 on 2022-11-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_alter_detsale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
