# Generated by Django 4.1 on 2022-11-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_alter_production_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detproduction',
            old_name='production',
            new_name='crea',
        ),
    ]
