# Generated by Django 4.1 on 2022-11-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_rename_production_detproduction_crea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detproduction',
            name='price',
        ),
    ]
