# Generated by Django 4.1 on 2022-11-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_remove_detproduction_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recy', models.CharField(choices=[('Caducado', 'Caducado'), ('Estetica', 'Estetica')], default='ls', max_length=10, verbose_name='Razon de reciclar')),
                ('cant', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reciclar',
                'verbose_name_plural': 'Reciclados',
                'ordering': ['id'],
            },
        ),
    ]
