# Generated by Django 4.1 on 2022-11-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_recycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recycle',
            name='recy',
            field=models.CharField(choices=[('Caducado', 'Caducado'), ('Estetica', 'Estetica')], default='Caducidad', max_length=10, verbose_name='Razon de retiro'),
        ),
    ]
