# Generated by Django 4.1 on 2022-11-22 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_alter_recycle_cant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
    ]
