# Generated by Django 4.1 on 2022-11-22 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0058_product_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
    ]
