# Generated by Django 4.1 on 2022-11-24 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_client_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de accion')),
                ('impo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MethodPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Cheque', 'Cheque'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=10, verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='typeFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de fondo')),
                ('impo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Fondo disponible')),
            ],
            options={
                'verbose_name': 'Tipo fondo',
                'verbose_name_plural': 'Tipos fondos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe')),
                ('typeMove', models.CharField(max_length=50, verbose_name='Tipo de movimiento')),
                ('PayName', models.CharField(max_length=50, verbose_name='Metodo de cobro o pago')),
                ('payNro', models.IntegerField(default=0, null=True, verbose_name='Numero de tarjeta o cheque')),
                ('payowner', models.CharField(max_length=150, null=True, verbose_name='Titular de tarjeta o cheque')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cierrecaja', verbose_name='Apertura o cierre de caja')),
                ('typeF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.typefunds', verbose_name='Tipo de fondo')),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
                'ordering': ['id'],
            },
        ),
    ]
