# Generated by Django 4.1 on 2022-11-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0061_fund_buy_fund_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='name',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='caja',
            field=models.CharField(choices=[('Apertura', 'Apertura'), ('Cierre', 'Cierre')], default='Apertura', max_length=50, verbose_name='Nombre de accion'),
        ),
    ]
