# Generated by Django 4.1 on 2022-11-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0062_remove_cierrecaja_name_cierrecaja_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.fund'),
            preserve_default=False,
        ),
    ]
