# Generated by Django 4.1 on 2022-11-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0063_remove_fund_buy_remove_fund_sale_sale_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefunds',
            name='methodpay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.methodpay', verbose_name='Metodos aceptado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='methodpay',
            name='pay',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Cheque o tarjeta', 'Cheque o tarjeta')], default='Efectivo', max_length=50, verbose_name='Metodo de pago'),
        ),
    ]
