# Generated by Django 4.1 on 2022-11-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0064_typefunds_methodpay_alter_methodpay_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='fund',
        ),
        migrations.AddField(
            model_name='fund',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='methodpay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.methodpay', verbose_name='Metodo de pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='typfund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.typefunds'),
            preserve_default=False,
        ),
    ]
