# Generated by Django 4.1 on 2022-11-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0065_remove_sale_fund_fund_sale_sale_methodpay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='PayName',
            field=models.CharField(max_length=50, null=True, verbose_name='Metodo de cobro o pago'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='closing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.cierrecaja', verbose_name='Apertura o cierre de caja'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
        ),
    ]
