# Generated by Django 4.1 on 2022-11-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0066_alter_fund_payname_alter_fund_closing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='PayName',
        ),
        migrations.AddField(
            model_name='fund',
            name='methodpay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.methodpay', verbose_name='Metodos aceptado'),
            preserve_default=False,
        ),
    ]
