# Generated by Django 4.1 on 2022-11-25 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0071_remove_withdraw_fund_withdraw_typef'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
    ]
