# Generated by Django 4.1 on 2022-11-25 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0072_withdraw_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='methodpay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.methodpay', verbose_name='Metodos aceptado'),
        ),
    ]
