# Generated by Django 4.1 on 2022-11-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0073_alter_fund_methodpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='methodpay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.methodpay', verbose_name='Metodos aceptado'),
            preserve_default=False,
        ),
    ]
