# Generated by Django 4.1 on 2022-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0074_alter_fund_methodpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='payNro',
            field=models.CharField(max_length=150, null=True, verbose_name='Numero de tarjeta o cheque'),
        ),
    ]
