# Generated by Django 4.1 on 2022-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0075_alter_fund_paynro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='impo',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='banco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='caja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Caja'),
        ),
    ]
