# Generated by Django 4.1 on 2022-11-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0076_remove_cierrecaja_impo_cierrecaja_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='caja',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='impor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe de cierre'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='typeF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.typefunds', verbose_name='Tipos de movimientos'),
            preserve_default=False,
        ),
    ]
