# Generated by Django 4.1 on 2022-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0077_remove_cierrecaja_banco_remove_cierrecaja_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='banco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe de banco'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='caja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe de caja'),
        ),
    ]
