# Generated by Django 4.1 on 2022-11-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0081_remove_cierrecaja_impor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaterials',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymaterials',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymaterials',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='categorymaterials',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
