# Generated by Django 4.1 on 2022-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0082_categorymaterials_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('cod_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=1)),
                ('datos_viejos', models.CharField(max_length=5000)),
                ('datos_nuevos', models.CharField(max_length=5000)),
                ('usuario', models.CharField(max_length=45)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
