# Generated by Django 4.1 on 2022-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0083_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='datos_nuevos',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='datos_viejos',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
