# Generated by Django 4.1 on 2022-11-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0084_alter_auditoria_datos_nuevos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='estado',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
