# Generated by Django 4.1 on 2022-11-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0085_cierrecaja_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='reason',
        ),
    ]
