# Generated by Django 4.1 on 2022-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0086_remove_withdraw_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detbuy',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detproduction',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detproduction',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detproduction',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detproduction',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detsale',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
