# Generated by Django 4.1 on 2022-11-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0087_buy_date_create_buy_date_update_buy_user_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_creation',
        ),
    ]
