# Generated by Django 4.1 on 2022-11-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0088_remove_category_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycle',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='recycle',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='recycle',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='recycle',
            name='user_update',
        ),
    ]
