# Generated by Django 4.1 on 2022-11-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0089_remove_recycle_date_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycle',
            name='recy',
        ),
    ]
