# Generated by Django 4.1 on 2022-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0090_remove_recycle_recy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
