# Generated by Django 4.1 on 2022-11-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0091_recycle_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='type',
            field=models.CharField(default=1, max_length=50, verbose_name='Accion'),
            preserve_default=False,
        ),
    ]
