# Generated by Django 4.1 on 2022-11-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0092_recycle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='user_create',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecycleMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad')),
                ('type', models.CharField(max_length=50, verbose_name='Accion')),
                ('fecha', models.DateField(auto_now=True)),
                ('user_create', models.CharField(max_length=45)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.materials')),
            ],
            options={
                'verbose_name': 'Reciclar',
                'verbose_name_plural': 'Reciclados',
                'ordering': ['id'],
            },
        ),
    ]
