# Generated by Django 4.1 on 2022-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0093_recycle_user_create_recyclematerials'),
    ]

    operations = [
        migrations.AddField(
            model_name='detbuy',
            name='status',
            field=models.CharField(default='p', max_length=150),
        ),
    ]
