# Generated by Django 4.1 on 2022-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0094_detbuy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detbuy',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
