# Generated by Django 4.1 on 2022-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0095_alter_detbuy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
