# Generated by Django 4.1 on 2022-11-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0100_remove_cierrecaja_informcaja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='close_informcaja',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='qper_informcaja',
        ),
    ]
