# Generated by Django 4.1 on 2022-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0101_remove_cierrecaja_close_informcaja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
