# Generated by Django 4.1 on 2022-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0105_remove_supplier_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_creation',
        ),
        migrations.AddField(
            model_name='client',
            name='user_create',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_update',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
